### ISSUE TITLE
2016/11/22 教育部會議要求修改

### ISSUE THREAD

**Issue by bobbytung** [caasi/bopomofo-handbook#1]
@caasi 這些我來處理

- [ ] 最後截圖製作成PDF檔案

- [x] 動畫連結移到「筆順」上頭

- [x] 表格內「筆順」改成「筆順動畫」

- [x] 加上注音音檔與Media Overlay

- [x] 最後示例因為國字寫法問題，改成圖片。

- [x] 月底提供中英文基本PDF申請ISBN

**Comment by caasi** [comment]
結果還是要生個 pdf 😭

**Comment by bobbytung** [comment]
動畫連結移到筆順上頭，因為是PNG圖片，看來要套色得用到Mask語法，想想乾脆改背景色（死
