### ISSUE TITLE
12/29日驗收

### ISSUE THREAD

**Issue by bobbytung** [caasi/bopomofo-handbook#11]
- [x] 做完入口頁面（含Counter、FAQ LightBox）
- [x] 補上輕聲到四聲的XML與SVG檔案
- [x] 處理Readium線上版顯示筆順動畫Mask的問題

驗收後修正

- [ ] 回收英文潤稿後修正英文版EPUB與HTML
- [ ] 繼上，申請英文版ISBN後補上
- [ ] @caasi #4 也要修正

**Comment by caasi** [comment]
加上 counter 了，請見 http://caasih.net/bopomofo-handbook/ 。

![2016-12-25 03 55 18](https://cloud.githubusercontent.com/assets/1164470/21468618/9393d2fc-ca56-11e6-85cf-93bc961c1595.png)

![2016-12-25 03 55 43](https://cloud.githubusercontent.com/assets/1164470/21468619/9932a7ce-ca56-11e6-8e7f-eece26493054.png)
